#!/usr/bin/env node
/**
 * create-castrater-app — scaffold a new castrater-app-kit project
 *
 * Usage:
 *   npx create-castrater-app my-app
 *   npx create-castrater-app my-app --force
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import prompts from 'prompts';
import pc from 'picocolors';

interface CliOptions {
  projectName: string;
  force: boolean;
}

interface ProjectAnswers {
  domain: string;
  apiDomain: string;
  farcaster: boolean;
  miniapp: boolean;
  wallets: boolean;
  proofs: boolean;
  inference: boolean;
  inferenceMode: 'none' | 'mock' | 'local' | 'remote';
  postgres: boolean;
  workers: boolean;
  storage: boolean;
}

function parseArgs(): CliOptions {
  const args = process.argv.slice(2);
  const force = args.includes('--force');
  const projectName = args.find((a) => !a.startsWith('--')) ?? 'my-castrater-app';
  return { projectName, force };
}

async function askQuestions(projectName: string): Promise<ProjectAnswers> {
  console.log('');
  console.log(pc.green('◆ castrater-app-kit scaffold'));
  console.log(pc.dim('  Minimal by default. Add features as needed.'));
  console.log('');

  const answers = await prompts(
    [
      {
        type: 'text',
        name: 'domain',
        message: 'App domain',
        initial: `app.${projectName}.com`,
      },
      {
        type: 'text',
        name: 'apiDomain',
        message: 'API domain',
        initial: `api.${projectName}.com`,
      },
      {
        type: 'confirm',
        name: 'farcaster',
        message: 'Include Farcaster support?',
        initial: false,
      },
      {
        type: 'confirm',
        name: 'miniapp',
        message: 'Include Farcaster Mini App support?',
        initial: false,
      },
      {
        type: 'confirm',
        name: 'wallets',
        message: 'Include qKMS wallet support?',
        initial: false,
      },
      {
        type: 'confirm',
        name: 'proofs',
        message: 'Include Quilibrium proof/storage adapters?',
        initial: false,
      },
      {
        type: 'confirm',
        name: 'inference',
        message: 'Include inference support?',
        initial: false,
      },
      {
        type: (prev: boolean) => (prev ? 'select' : null),
        name: 'inferenceMode',
        message: 'Inference mode',
        choices: [
          { title: 'mock (stub responses)', value: 'mock' },
          { title: 'local (Ollama)', value: 'local' },
          { title: 'remote (external API)', value: 'remote' },
        ],
        initial: 0,
      },
      {
        type: 'confirm',
        name: 'postgres',
        message: 'Include Postgres + Drizzle ORM?',
        initial: false,
      },
      {
        type: 'confirm',
        name: 'workers',
        message: 'Include BullMQ workers?',
        initial: true,
      },
      {
        type: 'confirm',
        name: 'storage',
        message: 'Include local file storage?',
        initial: false,
      },
    ],
    {
      onCancel: () => {
        console.log(pc.red('\nScaffold cancelled.'));
        process.exit(1);
      },
    }
  );

  return answers as ProjectAnswers;
}

function generateEnvExample(projectName: string, answers: ProjectAnswers): string {
  const lines = [
    '# Generated by create-castrater-app',
    '# Fill in real values before deploying.',
    '# NEVER commit secrets to version control.',
    '',
    'NODE_ENV=development',
    'LOG_LEVEL=info',
    '',
    `APP_DOMAIN=${answers.domain}`,
    `API_DOMAIN=${answers.apiDomain}`,
    `VITE_API_URL=http://localhost:4001`,
    '',
    'REDIS_URL=redis://localhost:6379',
  ];

  if (answers.postgres) {
    lines.push(
      '',
      `DATABASE_URL=postgresql://postgres:changeme@localhost:5432/${projectName}`,
      'POSTGRES_USER=postgres',
      'POSTGRES_PASSWORD=changeme',
      `POSTGRES_DB=${projectName}`
    );
  }

  if (answers.wallets) {
    lines.push(
      '',
      '# qKMS — leave empty to use MockQkmsClient (dev only)',
      'QKMS_URL=',
      'QKMS_API_KEY='
    );
  }

  if (answers.farcaster || answers.miniapp) {
    lines.push('', 'HYPERSNAP_URL=https://hypersnap.castrater.xyz');
  }

  if (answers.inference) {
    lines.push(
      '',
      `INFERENCE_MODE=${answers.inferenceMode ?? 'mock'}`,
      'INFERENCE_BASE_URL=http://localhost:11434',
      'INFERENCE_MODEL=llama3.2',
      'INFERENCE_EMBEDDING_MODEL=nomic-embed-text',
      'INFERENCE_TIMEOUT_MS=120000'
    );
  }

  if (answers.storage) {
    lines.push('', 'STORAGE_BASE_DIR=./storage');
  }

  return lines.join(os.EOL);
}

function generateCaddyfile(answers: ProjectAnswers): string {
  return [
    '# Caddy runs on the HOST — not inside Docker.',
    '# Copy to /etc/caddy/Caddyfile',
    '',
    `${answers.domain} {`,
    '  reverse_proxy 127.0.0.1:4000',
    '}',
    '',
    `${answers.apiDomain} {`,
    '  reverse_proxy 127.0.0.1:4001',
    '}',
  ].join(os.EOL);
}

function printNextSteps(targetDir: string, answers: ProjectAnswers): void {
  console.log('');
  console.log(pc.green('✅ Scaffold complete!'));
  console.log('');
  console.log(pc.bold('Next steps:'));
  console.log('');
  console.log(`  1. ${pc.cyan(`cd ${targetDir}`)}`);
  console.log(`  2. ${pc.cyan('cp .env.example .env')} — fill in your values`);
  console.log(`  3. ${pc.cyan('pnpm install')}`);
  console.log(`  4. ${pc.cyan('bash scripts/dev.sh')} — start dev environment`);
  console.log('');

  if (answers.miniapp) {
    console.log(pc.dim('  Mini App: rename apps/web/public/.well-known/farcaster.json.example'));
    console.log(pc.dim('            to farcaster.json and fill in your accountAssociation.'));
    console.log(pc.dim('  See: https://miniapps.farcaster.xyz/docs/specification'));
    console.log('');
  }

  if (answers.wallets) {
    console.log(pc.dim('  Wallets: set QKMS_URL + QKMS_API_KEY for production.'));
    console.log(pc.dim('           MockQkmsClient is unsafe for production.'));
    console.log('');
  }

  console.log(pc.dim('  Production: configure Caddy with Caddyfile.example'));
  console.log(pc.dim('  Firewall: only expose 22, 80, 443'));
  console.log('');
}

async function scaffold(opts: CliOptions): Promise<void> {
  const { projectName, force } = opts;
  const targetDir = path.resolve(process.cwd(), projectName);

  if (fs.existsSync(targetDir) && !force) {
    console.error(pc.red(`\n❌ Directory already exists: ${targetDir}`));
    console.error(pc.dim('   Use --force to overwrite.'));
    process.exit(1);
  }

  const answers = await askQuestions(projectName);

  console.log('');
  console.log(pc.dim('→ Creating project...'));

  // Create target directory
  fs.mkdirSync(targetDir, { recursive: true });

  // Write .env.example
  fs.writeFileSync(
    path.join(targetDir, '.env.example'),
    generateEnvExample(projectName, answers)
  );

  // Write Caddyfile.example
  fs.writeFileSync(
    path.join(targetDir, 'Caddyfile.example'),
    generateCaddyfile(answers)
  );

  // Write README stub
  fs.writeFileSync(
    path.join(targetDir, 'README.md'),
    `# ${projectName}\n\nGenerated by create-castrater-app.\n\nSee the [castrater-app-kit docs](https://github.com/i001962/castrater-app-kit) for full documentation.\n`
  );

  printNextSteps(projectName, answers);
}

scaffold(parseArgs()).catch((err) => {
  console.error(pc.red('Error:'), err instanceof Error ? err.message : err);
  process.exit(1);
});
